name: Dispatch Workflow

on:
  repository_dispatch:
    types: [start-workflow]

jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print a message
        run: echo "Workflow triggered by repository_dispatch event!"
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Cambia a la versión que necesitas

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client
          pip install nbconvert nbformat ipykernel jupyter
      
      - name: Run the Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute Dispatch_test.ipynb --output output.ipynb
